# render.yaml

services:
  - type: web
    name: mi-app-symfony
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php bin/console cache:clear --env=prod
      php bin/console doctrine:migrations:migrate --env=prod --no-interaction --allow-no-migration
    startCommand: XDG_CONFIG_HOME=/var/app/config /usr/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: mi-base-de-datos-pg
          property: connectionString

databases:
  - name: mi-base-de-datos-pg
    databaseName: piesaluddb
    user: hermez382
    plan: free