parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/images'
    uploads_url_base: '/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Registrar manualmente el comando
    App\Command\CreateUserCommand:
        tags: ['console.command']